apiVersion: batch/v1
kind: Deployment
metadata:
  name: tf-notebook
  app: tf-notebook
spec:
  template:
    spec:
      containers:
        - name: tf-notebook-container
          image:  nvcr.io/nvidia/tensorflow:20.12-tf1-py3
          command: ["/bin/sh"]
          args: ["-c", "jupyter lab  --notebook-dir=/workspace --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]
          resources:
            limits:
              nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: tf-notebook
  spec:
    selector:
      app: tf-notebook
    type: NodePort
    ports:
      - port: 8888
        nodePort: 30008
        name: http
